In [ ]:
10

###### Python

In [7]:
20

20

In [11]:
######## python

In [12]:
int (1,2)

TypeError: int() can't convert non-string with explicit base

In [13]:
13

13

In [14]:
str (3,6)

TypeError: str() argument 2 must be str, not int

In [16]:
int ("1,2")

ValueError: invalid literal for int() with base 10: '1,2'

In [17]:
int (2)

2

In [19]:
dir (list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [19]:
dir (list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [2]:
import time

start_time = time.time()
list1 = [x for x in range(1,1000000)]
list2 = [y for y in range(1,1000000)]

op = list(map(lambda x,y : x*y,list1,list2))
end_time = time. time()
print("Time taken:",end_time-start_time)

Time taken: 0.30203723907470703


In [7]:
import time
import numpy as np
start_time1 = time.time()
ar1 = np.array(list1)
ar2 = np.array(list2)
ar1*ar2

end_time1 = time.time()
print("Time taken:", end_time1-starat_time1)

Time taken: 0.14035272598266602


In [9]:
# 2-D declerations

d2 = np.array([[2,4,7],[5,8,23],[45,90,33]])
d2

array([[ 2,  4,  7],
       [ 5,  8, 23],
       [45, 90, 33]])

In [16]:
d2[1:2]

array([[ 5,  8, 23]])

In [11]:
d2[0][2]

7

In [12]:
np.max(d2[1])

23

In [13]:
np.min(d2[0])

2

In [15]:
np.average(d2[2])

56.0

In [17]:
d2[:,1].max()

90

In [19]:
d2[:,2].min()

7

In [20]:
d2.sum(axis=1)

array([ 13,  36, 168])

In [21]:
d2.sum(axis=0)

array([ 52, 102,  63])

In [23]:
d3 = np.array([[[1,2,3],[4,5,6]],[[24,8,5],[45,74,32]]])
d3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[24,  8,  5],
        [45, 74, 32]]])

In [35]:
11:00:50.595 NotebookApp Saving file at /My Project 5B5/First .ipynb

SyntaxError: invalid syntax (<ipython-input-35-cf8963ae79c7>, line 1)

In [36]:
for i in range(1,11):
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 10 

In [38]:
np.arange(i)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
for i in range(1,5,2):
    print(i)

1
3


In [44]:
np.arange(1,14,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5])

In [46]:
np.linspace(1,30,10)

array([ 1.        ,  4.22222222,  7.44444444, 10.66666667, 13.88888889,
       17.11111111, 20.33333333, 23.55555556, 26.77777778, 30.        ])

In [48]:
np.ones([5,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [50]:
np.tile(10,[5,5])

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [56]:
d4=np.array([[3,54,76,223,566,8,6,35,46,65],[745,678,2,3,684,3,7,354,97,74]])
d4

array([[  3,  54,  76, 223, 566,   8,   6,  35,  46,  65],
       [745, 678,   2,   3, 684,   3,   7, 354,  97,  74]])

In [57]:
np.linalg.inv(d4)

LinAlgError: Last 2 dimensions of the array must be square

# Random

In [62]:
np.random.randint(10,20)

13

In [59]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [63]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
np.arange(1,49).reshape(4,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])

In [64]:
np.arcsin(1)

1.5707963267948966

In [65]:
sec1=np.array(np.random.randint(1,10,[4,4]))
sec1

array([[9, 4, 9, 8],
       [7, 6, 3, 2],
       [6, 1, 9, 4],
       [9, 1, 1, 1]])

In [66]:
sec2=np.array(np.random.randint(10,20,[4,4]))
sec2

array([[12, 16, 13, 10],
       [13, 14, 12, 12],
       [15, 11, 10, 19],
       [19, 14, 16, 15]])

In [68]:
np.vstack((sec1,sec2))

array([[ 9,  4,  9,  8],
       [ 7,  6,  3,  2],
       [ 6,  1,  9,  4],
       [ 9,  1,  1,  1],
       [12, 16, 13, 10],
       [13, 14, 12, 12],
       [15, 11, 10, 19],
       [19, 14, 16, 15]])

In [69]:
np.hstack((sec1,sec2))

array([[ 9,  4,  9,  8, 12, 16, 13, 10],
       [ 7,  6,  3,  2, 13, 14, 12, 12],
       [ 6,  1,  9,  4, 15, 11, 10, 19],
       [ 9,  1,  1,  1, 19, 14, 16, 15]])

# dots

In [70]:
sec1.dot(sec2)

array([[447, 411, 383, 429],
       [245, 257, 225, 229],
       [296, 265, 244, 303],
       [155, 183, 155, 136]])

In [71]:
sec1.trace()

25